from __future__ import annotations

import json
import uuid
from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parents[1]


def rel(path: str | Path) -> str:
    path = Path(path)
    if path.is_absolute():
        try:
            path = path.relative_to(ROOT)
        except ValueError:
            pass
    return "../" + str(path).replace("\\", "/")


def markdown_cell(source: str) -> dict:
    return {
        "cell_type": "markdown",
        "id": uuid.uuid4().hex[:8],
        "metadata": {},
        "source": source.strip().splitlines(keepends=True),
    }


def table_from_records(records: list[dict], columns: list[str], limit: int | None = None) -> str:
    rows = records if limit is None else records[:limit]
    header = "| " + " | ".join(columns) + " |"
    sep = "| " + " | ".join(["---"] * len(columns)) + " |"
    body = []
    for row in rows:
        body.append("| " + " | ".join(str(row.get(col, "")).replace("|", "/") for col in columns) + " |")
    return "\n".join([header, sep, *body])


def df_to_markdown(df: pd.DataFrame, limit: int | None = None) -> str:
    rows = df if limit is None else df.head(limit)
    records = rows.fillna("").to_dict("records")
    return table_from_records(records, list(rows.columns))


def image_tag(path: str | Path, width: int = 180) -> str:
    return f'<img src="{rel(path)}" width="{width}">'


def gallery_table(rows: pd.DataFrame, image_col: str, columns: list[str], width: int = 180) -> str:
    header_cols = [*columns, "Figure"]
    header = "| " + " | ".join(header_cols) + " |"
    sep = "| " + " | ".join(["---"] * len(header_cols)) + " |"
    body = []
    for _, row in rows.iterrows():
        values = [str(row[col]) for col in columns]
        values.append(image_tag(row[image_col], width=width))
        body.append("| " + " | ".join(value.replace("|", "/") for value in values) + " |")
    return "\n".join([header, sep, *body])


def main() -> None:
    notebook_path = ROOT / "notebooks" / "01_kmeans_image_segmentation_report.ipynb"
    summary = json.loads((ROOT / "reports" / "metrics" / "workflow_summary.json").read_text(encoding="utf-8"))
    review = json.loads((ROOT / "reports" / "metrics" / "source_review.json").read_text(encoding="utf-8")) if (ROOT / "reports" / "metrics" / "source_review.json").exists() else {}
    balance = json.loads((ROOT / "reports" / "metrics" / "data_balance_report.json").read_text(encoding="utf-8"))
    comparison = pd.read_csv(ROOT / "reports" / "metrics" / "model_comparison.csv")
    clean = pd.read_csv(ROOT / "data" / "manifest" / "clean_landscape_manifest.csv")
    best = comparison.sort_values("ranking_score").groupby("image_id", as_index=False).head(1)
    all_outputs = comparison.sort_values(["image_id", "color_space", "use_xy", "k"])
    grid_paths = sorted((ROOT / "reports" / "figures").glob("*_k_grid_*.png"))

    balance_overview = {
        "clean_images": summary["clean_images"],
        "raw_images": summary["raw_images"],
        "real_selected": balance["real_selected"],
        "augmentation_selected": balance["augmentation_selected"],
        "max_augmentation": balance["max_augmentation"],
        "model_runs": summary["model_runs"],
    }
    source_counts = pd.Series(balance["source_counts"], name="count").reset_index().rename(columns={"index": "source"})
    query_counts = pd.Series(balance["query_counts"], name="count").reset_index().rename(columns={"index": "query"})

    cells = [
        markdown_cell(
            f"""# Final Notebook - K-Means Image Segmentation

## 1. Define Problem

The assignment requires segmenting a given image into `K` clusters using the K-Means algorithm. This project applies unsupervised pixel clustering to landscape images. Each pixel is represented by color-space features, assigned to the nearest centroid with Euclidean distance, and reconstructed by replacing the original pixel color with the centroid color.

This report is notebook-only and contains **0 code cells**. All code execution, model training, figures, labels, metrics, and review artifacts were generated by the project scripts before this notebook was written."""
        ),
        markdown_cell(
            """## 2. Assignment Mapping

| Assignment requirement | Concrete implementation |
|---|---|
| Load the image | `src/image_io.py` loads RGB images with PIL |
| Convert color space | RGB, HSV, and LAB are compared |
| Resize image | `max_side=128` for retraining efficiency |
| Flatten pixels | each image becomes `(height * width, n_features)` |
| Apply K-Means | NumPy implementation in `src/kmeans.py` |
| Assign nearest centroid | vectorized Euclidean distance |
| Update centroids | cluster means are recomputed each iteration |
| Repeat until convergence | controlled by `max_iter` and `tol` |
| Segment image | pixels are replaced by centroid colors |
| Visualize result | side-by-side and K-grid figures are exported |"""
        ),
        markdown_cell(
            f"""## 3. Workflow With Evidence

The implemented workflow is:

1. **Raw data collection**: image files under `{rel('data/raw/api')}` and raw manifest `{rel('data/manifest/raw_landscape_manifest.csv')}`.
2. **Data audit and balancing**: balanced clean manifest `{rel('data/manifest/clean_landscape_manifest.csv')}` and outlier/source report `{rel('reports/metrics/data_balance_report.json')}`.
3. **Preprocessing**: RGB loading, resize, color conversion, optional spatial `(x, y)` features.
4. **Training**: K-Means from scratch across `K=2..10`, color spaces `rgb/hsv/lab`, and `use_xy=false/true`.
5. **Outputs**: segmented figures in `{rel('reports/figures')}`, label arrays in `{rel('data/labels')}`, and model artifacts in `{rel('models')}`.
6. **Comparison and review**: metrics `{rel('reports/metrics/model_comparison.csv')}`, best model report `{rel('reports/metrics/best_model_by_image.json')}`, and source review `{rel('reports/metrics/source_review.json')}`."""
        ),
        markdown_cell(
            f"""## 4. Data Audit

The data audit computes width, height, aspect ratio, mean intensity, standard deviation, file size, source, and query for every clean image. IQR and z-score checks identify images that are far from the dataset distribution.

**Audit summary**

{table_from_records([balance_overview], list(balance_overview.keys()))}

**Feature ranges after balancing**

| Feature | Minimum | Mean | Maximum |
|---|---:|---:|---:|
| width | {clean['width'].min()} | {clean['width'].mean():.2f} | {clean['width'].max()} |
| height | {clean['height'].min()} | {clean['height'].mean():.2f} | {clean['height'].max()} |
| mean intensity | {clean['mean_intensity'].min():.2f} | {clean['mean_intensity'].mean():.2f} | {clean['mean_intensity'].max():.2f} |
| std intensity | {clean['std_intensity'].min():.2f} | {clean['std_intensity'].mean():.2f} | {clean['std_intensity'].max():.2f} |"""
        ),
        markdown_cell(
            f"""## 5. Data Balancing

The selected training data keeps 20 clean landscape images. The balance rule prioritizes real Wikimedia/raw images, filters extreme quality outliers when enough candidates exist, and caps augmentation at 8 images. In this final run, the pipeline selected **{balance['real_selected']} real images** and **{balance['augmentation_selected']} augmented images**.

**Source distribution**

{df_to_markdown(source_counts)}

**Query distribution**

{df_to_markdown(query_counts)}"""
        ),
        markdown_cell(
            """## 6. Preprocessing

Every selected image is resized to `max_side=128`, then represented in RGB, HSV, or LAB. The experiment also compares two feature modes:

- color-only features: `[c1, c2, c3]`
- color + spatial features: `[c1, c2, c3, x, y]`

No ground-truth masks, semantic labels, or deep learning segmentation models are used."""
        ),
        markdown_cell(
            f"""## 7. Training Grid

The training grid is fixed and reproducible:

| Dimension | Values |
|---|---|
| Images | {summary['clean_images']} |
| K values | {summary['k_values']} |
| Color spaces | {summary['color_spaces']} |
| Spatial modes | {summary['use_xy_modes']} |
| Expected runs | {summary['clean_images']} × {len(summary['k_values'])} × {len(summary['color_spaces'])} × {len(summary['use_xy_modes'])} = {summary['model_runs']} |

Each run saves a segmented image, side-by-side comparison, pixel label array, and `.npz` K-Means artifact."""
        ),
        markdown_cell(
            f"""## 8. Model Comparison

The comparison uses unsupervised internal metrics because the assignment does not provide ground-truth segmentation masks.

| Metric | Direction | Meaning |
|---|---|---|
| silhouette_sample | higher | better cluster separation |
| davies_bouldin_sample | lower | lower within/between cluster ratio |
| calinski_harabasz_sample | higher | stronger between-cluster dispersion |
| inertia_per_pixel | lower | pixels closer to assigned centroids |
| cluster_balance | higher | fewer collapsed tiny clusters |
| ranking_score | lower | combined selection score |

**Top 15 model runs**

{df_to_markdown(comparison.sort_values('ranking_score')[['image_id','k','color_space','use_xy','silhouette_sample','davies_bouldin_sample','inertia_per_pixel','cluster_balance','ranking_score']].head(15))}"""
        ),
        markdown_cell(
            f"""## 9. Best Model Selection

The best model for each image is the run with the lowest `ranking_score`. This balances separation, compactness, and cluster stability.

{df_to_markdown(best[['image_id','k','color_space','use_xy','silhouette_sample','davies_bouldin_sample','ranking_score']])}"""
        ),
        markdown_cell(
            f"""## 10. Best Output Image Gallery

These figures show the best-ranked side-by-side output for each selected image.

{gallery_table(best, 'output_comparison', ['image_id','k','color_space','use_xy','ranking_score'], width=220)}"""
        ),
        markdown_cell(
            f"""## 11. K-Grid Highlights

K-grid figures compare how segmentation changes as `K` increases.

{''.join(f'<p>{image_tag(path, width=260)}<br>{Path(path).name}</p>\\n' for path in grid_paths[:24])}"""
        ),
        markdown_cell(
            f"""## 12. Output Image Gallery - All Trained Figures

This appendix lists every trained side-by-side comparison image generated by the retraining workflow.

{gallery_table(all_outputs, 'output_comparison', ['image_id','k','color_space','use_xy'], width=150)}"""
        ),
        markdown_cell(
            f"""## 13. Final Review

The review script checks data balance, expected model-run count, metric completeness, artifact existence, notebook structure, and assignment alignment.

| Check | Result |
|---|---|
| clean images | {review.get('clean_images', summary['clean_images'])} |
| model runs | {review.get('model_runs', summary['model_runs'])} |
| expected model runs | {review.get('expected_model_runs', summary['model_runs'])} |
| assignment alignment | {review.get('alignment', 'K-Means image segmentation with landscape images')} |

The final notebook has no code cells. The project remains aligned with the original K-Means Image Segmentation exercise: load image, convert color space, resize, flatten pixels, cluster by K-Means, reconstruct segmented image, and visualize original versus segmented output."""
        ),
    ]
    notebook = {
        "cells": cells,
        "metadata": {
            "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
            "language_info": {"name": "python", "pygments_lexer": "ipython3"},
        },
        "nbformat": 4,
        "nbformat_minor": 5,
    }
    notebook_path.parent.mkdir(parents=True, exist_ok=True)
    notebook_path.write_text(json.dumps(notebook, indent=2), encoding="utf-8")
    print(str(notebook_path).encode("unicode_escape").decode("ascii"))


if __name__ == "__main__":
    main()
